version: '3.4'

services:
  bonds.app.api:
    image: almirok/bonds:latest
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Bonds=Server=postgres;Port=5432;User Id=${POSTGRES_USER};Password=${POSTGRES_PW};Database=${POSTGRES_DB};
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always