// <auto-generated />
using System;
using Bonds.DataProvider;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bonds.DataProvider.Migrations
{
    [DbContext(typeof(BondsContext))]
    [Migration("20240901082200_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bonds.DataProvider.Entities.BondEntity", b =>
                {
                    b.Property<string>("ISIN")
                        .HasColumnType("text");

                    b.Property<double?>("Ask")
                        .HasColumnType("double precision");

                    b.Property<double?>("Bid")
                        .HasColumnType("double precision");

                    b.Property<double>("Change")
                        .HasColumnType("double precision");

                    b.Property<double>("CouponValue")
                        .HasColumnType("double precision");

                    b.Property<double>("High")
                        .HasColumnType("double precision");

                    b.Property<double>("Last")
                        .HasColumnType("double precision");

                    b.Property<double>("Low")
                        .HasColumnType("double precision");

                    b.Property<double>("MarketPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("MarketPriceToday")
                        .HasColumnType("double precision");

                    b.Property<double>("Open")
                        .HasColumnType("double precision");

                    b.Property<double>("PriceMinusPrevWaPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("Qty")
                        .HasColumnType("double precision");

                    b.Property<double>("SeqNum")
                        .HasColumnType("double precision");

                    b.Property<double?>("Spread")
                        .HasColumnType("double precision");

                    b.Property<double>("TradesCount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ValToday")
                        .HasColumnType("bigint");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.Property<long>("VolToday")
                        .HasColumnType("bigint");

                    b.Property<double>("WaPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("Yield")
                        .HasColumnType("double precision");

                    b.Property<double>("YieldAtWaPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("YieldLastCoupon")
                        .HasColumnType("double precision");

                    b.HasKey("ISIN");

                    b.ToTable("Bonds");
                });

            modelBuilder.Entity("Bonds.DataProvider.Entities.BondExtendedEntity", b =>
                {
                    b.Property<string>("ISIN")
                        .HasColumnType("text");

                    b.Property<long?>("EmitterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ISIN");

                    b.ToTable("BondsExtended");
                });
#pragma warning restore 612, 618
        }
    }
}
